// Copyright (c) 2025 complex (complex@ft.hn)
// See LICENSE for licensing information

package lang

// init initializes the languages slice
// Language wordlists are imported from lang_*.go files (generated by convert_lang.py)
func init() {
	// Languages are initialized in the order they appear in the C implementation
	// This matches the order in src/lang.c
	languages = []*Language{
		&LangEn,  // English
		&LangJp,  // Japanese
		&LangKo,  // Korean
		&LangEs,  // Spanish
		&LangFr,  // French
		&LangIt,  // Italian
		&LangCs,  // Czech
		&LangPt,  // Portuguese
		&LangZhS, // Chinese (Simplified)
		&LangZhT, // Chinese (Traditional)
	}
}

