// Copyright (c) 2025 complex (complex@ft.hn)
// See LICENSE for licensing information

package polyseed

// init initializes the languages slice
// Language wordlists are imported from lang_*.go files (generated by convert_lang.py)
func init() {
	// Languages are initialized in the order they appear in the C implementation
	// This matches the order in src/lang.c
	languages = []*Language{
		&langEn,  // English
		&langJp,  // Japanese
		&langKo,  // Korean
		&langEs,  // Spanish
		&langFr,  // French
		&langIt,  // Italian
		&langCs,  // Czech
		&langPt,  // Portuguese
		&langZhS, // Chinese (Simplified)
		&langZhT, // Chinese (Traditional)
	}
}

